### ISSUE TITLE
SHM info disappears after reloading nginx

### ISSUE THREAD

**Issue by Perlovka** [ZigzagAK/ngx_sysinfo#1]
nginx.conf:
```
lua_shared_dict dict1 2m;

upstream test1 {
    zone shm1 128k;
    server 127.0.0.1;
}

upstream test2 {
    zone shm2 128k;
    server 127.0.0.1;
}
```

curl  http://localhost/sysinfo:

`
{"shared_memory": [{"name": "dict1","pages":508,"free_pages":506,"used":"0%","slab":[{"size":8,"used":0,"total":0,"fails":0},{"size":16,"used":0,"total":0,"fails":0},{"size":32,"used":0,"total":0,"fails":0},{"size":64,"used":64,"total":4096,"fails":0},{"size":128,"used":128,"total":4096,"fails":0},{"size":256,"used":0,"total":0,"fails":0},{"size":512,"used":0,"total":0,"fails":0},{"size":1024,"used":0,"total":0,"fails":0},{"size":2048,"used":0,"total":0,"fails":0}],"summary":{"total":2080768,"used":192}},{"name": "shm1","pages":31,"free_pages":26,"used":"16%","slab":[{"size":8,"used":8,"total":4032,"fails":0},{"size":16,"used":32,"total":4064,"fails":0},{"size":32,"used":32,"total":4064,"fails":0},{"size":64,"used":0,"total":0,"fails":0},{"size":128,"used":384,"total":4096,"fails":0},{"size":256,"used":256,"total":4096,"fails":0},{"size":512,"used":0,"total":0,"fails":0},{"size":1024,"used":0,"total":0,"fails":0},{"size":2048,"used":0,"total":0,"fails":0}],"summary":{"total":126976,"used":712}},{"name": "shm2","pages":31,"free_pages":26,"used":"16%","slab":[{"size":8,"used":8,"total":4032,"fails":0},{"size":16,"used":32,"total":4064,"fails":0},{"size":32,"used":32,"total":4064,"fails":0},{"size":64,"used":0,"total":0,"fails":0},{"size":128,"used":384,"total":4096,"fails":0},{"size":256,"used":256,"total":4096,"fails":0},{"size":512,"used":0,"total":0,"fails":0},{"size":1024,"used":0,"total":0,"fails":0},{"size":2048,"used":0,"total":0,"fails":0}],"summary":{"total":126976,"used":712}}]}
`

After ```systemctl reload nginx``` only the dict1 info is available:

`{"shared_memory": [{"name": "dict1","pages":508,"free_pages":506,"used":"0%","slab":[{"size":8,"used":0,"total":0,"fails":0},{"size":16,"used":0,"total":0,"fails":0},{"size":32,"used":0,"total":0,"fails":0},{"size":64,"used":64,"total":4096,"fails":0},{"size":128,"used":128,"total":4096,"fails":0},{"size":256,"used":0,"total":0,"fails":0},{"size":512,"used":0,"total":0,"fails":0},{"size":1024,"used":0,"total":0,"fails":0},{"size":2048,"used":0,"total":0,"fails":0}],"summary":{"total":2080768,"used":192}}]}`

**Comment by ZigzagAK** [comment]
@Perlovka 
Thank's for the issue.
Fixed.

**Comment by Perlovka** [comment]
Thanks ;)
